### ISSUE TITLE
unburden-home-dir can't move .cache folder because find command already use it

### ISSUE THREAD

**Issue by MurzNN** [xtaran/unburden-home-dir#10]
I configure moving .cache folder on Ubuntu 14.04 with KDE environment, but each time on login I see in logs this problem:
```
WARNING: Can't handle /home/user1/.cache: in use, not (re)moving. Process list:
   3813 (find)
   3813 (find)
```
So .cache folder will never moved to unburden location.
 
Seems that unburden-home-dir script launch `find` process, that don't finish on this check. How can I fix the problem? Maybe can help sleep command for some seconds before this check?

**Comment by MurzNN** [comment]
I have fix this via this not so good, but working hack:
```
350c350
<         $lsof_output = `find '$item' -print0 | buffer | xargs -0 lsof -F c`;
---
>         $lsof_output = `find '$item' -print0 | buffer | xargs -0 lsof -F c | grep -v 'find'`;
```

**Comment by xtaran** [comment]
Thanks for the bug report, but that's from an rather old version where I at most will provide security fixes.

And the affected code has been removed respectively replaced with the release of unburden-home-dir version 0.3.2.3 in May 2014.

So the issue should no more be present in Ubuntu 16.04 LTS (current LTS release) or Debian 8 Jessie (currently "oldstable") or later releases.

Hence closing the issue.
