### ISSUE TITLE
major browsers cache location is wrong

### ISSUE THREAD

**Issue by jeka** [xtaran/unburden-home-dir#9]
I hope that I am not wrong on this:
Looking at contents of /etc/unburden-home-dir.list
- google-chrome
I don't see files .config/google-chrome/*/Thumbnails\[-journal\]
(actually I am using beta channel and dir for me is .config/google-chrome-beta, maybe its good idea to consider beta users too or maybe even unstable?)
$ find . -name Thumbnails (in $HOME) returns nothing, so its not moved, just not valid (at least for beta)
but there are 2 cache dirs at ~/.cache/google-chrome-beta/Default/
google-chrome-beta-46.0.2490.13-1.x86_64

- for firefox
cache dirs are under  ./.cache/mozilla/firefox/{profile}/ 
there is no Cache.Trash but few more 
firefox-40.0.3-1.fc22.x86_64

I guess I can fork/patch/create pull request but maybe that is not valid for every distribution,
I really have no idea.

**Comment by xtaran** [comment]
The lists contain gathered locations from many versions and should not only work with the current version. All paths in there have been seen in the past at least once.

`~/.cache/mozilla/firefox/{profile}/ ` and `~/.cache/google-chrome-beta/Default/` are already caught by handling `~/.cache`.

So I currently see no issue in here. Feel free to reopen if you disagree.

**Comment by jeka** [comment]
I knew that maybe I am missing something. Actually I am using Korora and they comment  .cache  dir alone for some reason 
Anyway, sorry for the noise.
